import { LeagueMemberResponse, LeagueMemberStatus } from "src/_types/type";

export const mockData: LeagueMemberResponse[] = [
  {
    id: 1,
    userId: 1,
    username: "biotechnological",
    leagueId: 1,
    status: LeagueMemberStatus.ACTIVE,
    totalScore: 1200,
    goalAmount: 1000,
  },
  {
    id: 2,
    userId: 2,
    username: "도롱이",
    leagueId: 1,
    status: LeagueMemberStatus.INACTIVE,
    totalScore: 1200,
    goalAmount: 1000,
  },
  {
    id: 3,
    userId: 3,
    username: "티끌모아왕티끌",
    leagueId: 1,
    status: LeagueMemberStatus.INACTIVE,
    totalScore: 1200,
    goalAmount: 1000,
  },
  {
    id: 4,
    userId: 4,
    username: "도롱도롱도로로",
    leagueId: 1,
    status: LeagueMemberStatus.INACTIVE,
    totalScore: 1200,
    goalAmount: 1000,
  },
  {
    id: 5,
    userId: 5,
    username: "저축왕루피",
    leagueId: 1,
    status: LeagueMemberStatus.ACTIVE,
    totalScore: 1200,
    goalAmount: 1000,
  },
  {
    id: 6,
    userId: 6,
    username: "저축고수",
    leagueId: 1,
    status: LeagueMemberStatus.INACTIVE,
    totalScore: 1200,
    goalAmount: 1000,
  },
  {
    id: 7,
    userId: 7,
    username: "홍길동이",
    leagueId: 1,
    status: LeagueMemberStatus.INACTIVE,
    totalScore: 1200,
    goalAmount: 1000,
  },
  {
    id: 8,
    userId: 8,
    username: "백두산",
    leagueId: 1,
    status: LeagueMemberStatus.INACTIVE,
    totalScore: 1200,
    goalAmount: 1000,
  },
];
